
<br style="font-weight: bold;" />
<div style="text-align: center;"><span style="font-weight: bold;">Clan Name:</span>
  <br />Divine Intervention
  <br />
  <br />
</div>
<div style="text-align: center;"><span style="font-weight: bold;">Clan Leaders:</span>
  <br />Di.Citles, Di.OneX, Di.Sovereign
  <br />
  <br /><span style="font-weight: bold;">Clan Motto:</span>
  <br />People. Passion. Performance.
  <br />
  <br style="font-weight: bold;" /><span style="font-weight: bold;">Clan Colors:</span>
  <br /><span style="color: rgb(39, 115, 130);">Blue</span>, <span style="color: rgb(255, 255, 255);">White</span>, Black, <span style="color: rgb(128, 128, 128);">Gray
    <br />
    <br /><span style="font-weight: bold; color: rgb(0, 0, 0);">Forums:</span>
    <br /><span style="color: rgb(255, 255, 255);">www.ClanDi.net/forums/</span>
    <br /></span>
</div>
<br />
<div style="text-align: center;"><span style="font-weight: bold;">Current Divisions:</span>
  <br />BW, CS, CS:S, DoD, GoW, EoW, D2, WoW, WC3
  <br />
  <br /><span style="font-weight: bold;">Clan Channel:</span>
  <br />Clan Di (For All B.net Games)
  <br />
  <br /><span style="font-weight: bold;">CS Server:
    <br /></span>8.9.9.185:27015
  <br />
  <br style="font-weight: bold;" /><span style="font-weight: bold;">CS Private Server:</span>
  <br style="font-weight: bold;" />Coming Soon
  <br />
  <br style="font-weight: bold;" /><span style="font-weight: bold;">CS:S Server:</span>
  <br style="font-weight: bold;" />Coming Soon
  <br />
  <br style="font-weight: bold;" /><span style="font-weight: bold;">CS:S Private Server:</span>
  <br style="font-weight: bold;" />Coming Soon
  <br />
  <br />
  <br style="font-weight: bold;" />
  <br style="font-weight: bold;" />
</div>
<br style="font-weight: bold;" />
<br style="font-weight: bold;" />
<br style="font-weight: bold;" />
<br style="font-weight: bold;" />
<br style="font-weight: bold;" />
<br />
<br />
