
<div style="text-align: center;"><h1 style="color: rgb(18, 168, 255); font-weight: bold; font-style: italic;">FAQs</h1><span style="color: rgb(66, 121, 194); font-weight: bold;"><hr />
    <br />
    <br />Q: What does Di stand for?</span>
  <br />A: Di is our clan name, Divine Intervention
  <br />
  <br /><span style="color: rgb(66, 121, 194); font-weight: bold;">Q: Who are the leaders of Di?</span>
  <br />A: Di.Citles, Di.OneX and Di.Sovereign
  <br />
  <br /><span style="color: rgb(66, 121, 194); font-weight: bold;">Q: Can I join Di?</span>
  <br />A:
If you are qualified, absolutely, please refer to our How to Join page
or AIM one of our eligible recruiters (Ranks WO1 and up)
  <br />
  <br /><span style="color: rgb(66, 121, 194); font-weight: bold;">Q: What games does Di support?</span>
  <br />A:
Currently, Di supports a total of 10 games, such as: StarCraft:
BroodWar, Diablo2: Lord of Destruction, WarCraft3: The Frozen Throne,
CounterStrike 1.6, CounterStrike: Source, World of WarCraft: The
Burning Crusade, Halo3, Halo: PC, Guild Wars and Star Wars: Empire at
War. 
  <br />
  <br />Q: Can Di make a new division for a game I play?
  <br />A: If
you can find us 10 members, we’ll grant you a squad. Get 20 and you
have yourself a division. A General must approve of it first, and if it
requires any funding or possible maintenance, a Commander might need to
approve of it too
  <br />
  <br style="font-weight: bold; color: rgb(66, 121, 194);" /><span style="font-weight: bold; color: rgb(66, 121, 194);">Q: So, if Di is on Battle.Net, which realm do they play on?</span>
  <br />A: Right now, Di is based on USEast/Azeroth for all Battle.Net games
  <br />
  <br /><span style="color: rgb(66, 121, 194); font-weight: bold;">Q: Where can I find the server information for all of our servers?</span>
  <br />A: On the Basic Information page, you should be able to find all of the servers that we run and maintain
  <br />
  <br /><span style="font-weight: bold; color: rgb(66, 121, 194);">Q: How many ranks are there in Di?</span>
  <br />A: There are 25 ranks in Di that all members can climb. 
  <br />
  <br /><span style="font-weight: bold; color: rgb(66, 121, 194);">Q: I want to be a General, can I be one?</span>
  <br />A: Administration is determined by Di Commanders, but always remember no rank is unreachable.
  <br />
  <br /><span style="color: rgb(66, 121, 194); font-weight: bold;">Q: My friend wants to join, can he?</span>
  <br />A: Absolutely, as long as he fits our member criteria
  <br />
  <br style="font-weight: bold; color: rgb(66, 121, 194);" /><span style="font-weight: bold; color: rgb(66, 121, 194);">Q: How can I recruit?</span>
  <br />A:
To be able to recruit, you must be a member of a recruiting squad and a
high enough rank to be eligible to receive the console. If you fit both
of those, then apply and simply add him through your console. If you
aren’t eligible for your console yet, kindly get another member to do
it for you. The more the merrier!
  <br />
  <br /><span style="color: rgb(66, 121, 194); font-weight: bold;">Q: Can I play more than one game while in Di?</span>
  <br />A:
Of course you can! If you half of the games that Di supports, feel free
to play them all. By doing this, you get to see how other divisions are
run and you get to meet many more members than if you were just a one
division member
  <br />
  <br /><span style="color: rgb(66, 121, 194);">Q: Does Di have forums?</span>
  <br />A: www.clandi.net/forums.  Feel free to visit them whenever you like
  <br />
  <br /><span style="font-weight: bold; color: rgb(66, 121, 194);">Q: Do I have to register using my Di name?</span>
  <br />A: We would appreciate if you did.  It makes it much easier for us to distinguish who’s in the clan and who isn’t
  <br />
  <br /><span style="font-weight: bold; color: rgb(66, 121, 194);">Q: How many times do I have to login to be in Di?</span>
  <br />A:
There is no maximum amount, but we ask all members to be able to commit
a minor 10 seconds to logging in everyday. It shows your appreciation
for the time and effort that we spend towards bettering your gaming
experience
  <br />
  <br style="color: rgb(66, 121, 194);" /><span style="color: rgb(66, 121, 194); font-weight: bold;">Q: I do GFX…does Di do GFX too?</span>
  <br />A: We sure do!
Check out our GFX section on our forums and post your portfolio for us
to see. We pride ourselves in the skill of our members, so if you have
something to bring to the table, or just want to help out, feel free to
volunteer and make us some awesome GFX!
  <br />
  <br /><span style="font-weight: bold; color: rgb(66, 121, 194);">Q: Can I hack while in Di?</span>
  <br />A:
Clan Di has a 0 tolerance towards hacking of any kind. We are a clean
gaming clan, and hacks only make members unhappy. We would prefer if
you did not hack, and if you are caught hacking, you will be warned and
possibly removed from our website
  <br />
  <br /><span style="color: rgb(66, 121, 194); font-weight: bold;">Q: While playing a game supported by Di, do I have to be on my Di account?</span>
  <br />A:
Much like on the forums, we prefer it because it is easier for us to
know who is who. If you have a very commonly used SMURF account, please
put your Di account information in its profile so that we can tell who
you are
  <br />
  <br /><span style="color: rgb(66, 121, 194); font-weight: bold;"> Q: Does Di have a ventrilo or teamspeak server?</span>
  <br />A:
Of course we do, it’s just one of the perks of being a part of this
clan. You can find the information available on the BASIC INFORMATION
page
</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
