
<p align="center" style="text-align: center;" class="MsoNormal"><span style="font-size: 22pt; font-family: Andalus;">Clan History<o:p></o:p></span><span style="font-size: 16pt; font-family: Andalus;"><o:p>
      <br /></o:p></span></p>
<p align="center" style="text-align: center;" class="MsoNormal"><span style="font-size: 16pt; font-family: Andalus;"><o:p><hr /></o:p></span></p>
<p class="MsoNormal"><span style="font-size: 16pt; font-family: Andalus;"><span style="font-weight: bold;">The Dawn
of Clan Di</span><o:p></o:p></span>
  <br /><span style="font-family: Andalus;">The idea to form a new
beginning spawned from the minds of Di.Citles and Di.OneX who were currently
active members of Clan AH.<span>&nbsp; </span>Both having
quite an influence in AH, Di.Citles and Di.OneX had decided although their time
in AH was great, the only way they would ever be able to see themselves as true
leaders was to take the risk and do what many believed impossible.<span>&nbsp; </span>As both previous Clan AH leaders knew, they
were not the only members that felt this way, and AH was not the only clan with
some inner conflicts.<span>&nbsp; </span>With this
knowledge, Di.Citles went in search of a previous leader he had come to
respect, Di.Sovereign, a previous General of Clan DF.<span>&nbsp; </span>Di.Sovereign listened to the idea, and was ecstatic
at the chance to come together as leaders from across the gaming world and
develop something with the potential to rival the gaming world.<span>&nbsp; </span>The planning began; the original founders of
clan Di commenced to creating names, tags, ideas, and scripts to build their
new dream.<span>&nbsp; </span>Finally, they came to agree
that “Divine Intervention” was the perfect name, as they all felt it was
necessary that they intervene in their current clanning environment.<span>&nbsp; </span>The team work was amazing, all three
commanders quickly grew on each other, and Clan Di began to form.<span>&nbsp; </span>However, this was not a three man
success.<span>&nbsp; </span>All three commanders informed
some of their closes friends what they were planning, and asked them to keep it
secret until Di was ready for release.<span>&nbsp;</span>Although the information was leaked, and Di.Citles was removed as a
Commander in Clan AH, the plans for Di remained in tact and the progression
continued forward.<span>&nbsp; </span>Di was officially
released on September 27<sup>th</sup>, 2007.<span>&nbsp;</span>This release date was earlier then the commanders had originally hoped,
but with the strong support for fellow leaders, members, and new comers, the early
dawn was thriving.<span>&nbsp; </span>Upon release, Clan Di
established it’s vision, one shared by many friends around the gaming
world.<span>&nbsp; </span>The vision was summed up in three
words, “People. Passion. Performace”, and these three terms were used to define
the meaning behind Clan Di.<span>&nbsp;</span>Deathwing.of.AH, Kuka.of.AH, Merlin.of.AH, Zim.of.AH, DF-Backdraft,
NoUNO.of.AH, Salvation.of.AH, and seefour.of.AH were all administration members
in clan AH and clan DF, and all of them decided to seek out new potential by
joining Clan Di as its new Administration Team.<span>&nbsp;</span>Shortly after, previous leader DF-madmark, who had broken off of DF to
make his own clan, also merged into Di to make the final member in Clan Di’s
original Administration Members.<span>&nbsp;&nbsp; </span>The
potential in Clan Di was looking exceptionally high, and the ideas from Members,
Officers, Division Leaders, and Administration Members seemed infinite.<span>&nbsp; </span>Di has dawned, the egg has hatched, and only
time will expose the essence of this clan.</span></p>
<p class="MsoNormal"><hr /><span style="font-family: Andalus;"><o:p></o:p></span></p>
