
<br />
<div class="content_back">
  <div align="center">
    <div class="content_header"><h3 class="content_box_header">Welcome</h3>
    </div>
  </div><hr class="cb" />
  <p class="cb">Welcome to Clan Divine Intervention.  We are a multi-game clan spreading across several countries.  If you would like to join, or are interested in an alliance, please contact a member.  If you have a question related to the Sovereign Clan Manager you can contact me on AIM - Di Sovereign or by email - sovereign@clandi.net</p><hr class="cb" />
  <div class="content_box_footer"></div>
</div>

<div>
<img src="images/home_splash/<?php echo( rand( 1, 5 ) ) ?>.jpg" />
</div>
