
<div style="MARGIN-LEFT: 10px; WIDTH: 450px">
  <br />
  <div align="center" class="content_back">
    <div class="content_header"><h3 class="content_box_header">How to Join</h3>
    </div>
  </div>
  <div class="content_back"><hr align="center" width="300" class="cb" />
  </div>
  <p class="content_back">&nbsp;&nbsp;&nbsp;Basic Information For In Game Manners </p>
  <div class="content_back">&nbsp;&nbsp;&nbsp;* On most games (cs, css, halo 3, etc) you need a 2:1 Ratio. 
  </div>
  <div class="content_back">&nbsp;&nbsp;&nbsp;* Have GM (Good Manner) and don't BM (Bad Mouth) 
  </div>
  <div class="content_back">&nbsp;&nbsp;&nbsp;* Usually we ask you for a tryout, but you may ask us for a tryout. 
  </div>
  <div class="content_back">&nbsp;&nbsp;&nbsp;* Remember the first <span style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: Verdana">impression</span> is usually the best <span style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: Verdana">impression</span>. 
    <br />
    <br />Basic Information On How To Join 
    <br />
    <div class="content_back">&nbsp;&nbsp;&nbsp;* If there is a certain game that you would like to join you make look at the <a href="/index.php?view=members.php">members page</a> and contact 1 of the administrative. 
    </div>
    <div class="content_back">&nbsp;&nbsp;&nbsp;* You may also visit the <a href="/forums/index.php?">forums</a>. You will have to <a href="/forums/index.php?act=Reg&amp;CODE=00">register</a> but you have to make a topic in the<a href="/forums/index.php?showforum=7"> Joining Section. </a>
    </div>
    <div class="content_back">&nbsp;&nbsp;&nbsp;* Also if you are in game and see a member that has a [R] that usually means they are a recruitor and they can recruit you in the game. 
    </div>
    <br /><span class="style2">&nbsp;<span class="style7">&nbsp;&nbsp;In the Future we will have the Trial Member for people that want to tryout. 
        <br />&nbsp;&nbsp;&nbsp;The following information is for the upcoming update. </span></span>
    <br />
    <br /><span class="style4">&nbsp;&nbsp;&nbsp;Trying Out </span>
    <div class="content_back">&nbsp;&nbsp;&nbsp;*Again each game it is different. So to learn more click on 1 of the games below. 
    </div>
    <div class="content_back">&nbsp;&nbsp;&nbsp;* You must get 4 votes within a 7 day period. (or a General may add you) 
    </div>
    <div class="content_back">&nbsp;&nbsp;&nbsp;* DO NOT ASK for votes! This will get you a negative vote. 
    </div>
    <br />
  </div>
  <ul>&nbsp;
  </ul>
  <p align="center" class="content_back">&nbsp;&nbsp;&nbsp;Please Click on 1 of the following games to get information on how to join 
    <br />&nbsp;&nbsp;&nbsp;<a href="#Cs16">Counter-Strike 1.6</a>, <a href="#Css">Counter-Strike:Source</a>, <a href="#d2">Diablo 2</a>, <a href="#H3">Halo 3</a>, <a href="#wow">World of Warcraft</a>, <a href="#w3">Warcraft III</a>, 
    <br /></p>
  <div class="content_back"><hr align="center" width="300" class="cb" />
  </div><h3 align="center" class="content_back">Counter-Strike 1.6<a name="Cs16"></a></h3>
  <p align="left" class="content_back">&nbsp;&nbsp;&nbsp; How to get all 7 Votes!</p>
  <div align="left" class="content_back">&nbsp;&nbsp;&nbsp; * Be active in Vent 
  </div>
  <div align="left" class="content_back">&nbsp;&nbsp;&nbsp; * Be active in Servers 
  </div>
  <div align="left" class="content_back">&nbsp;&nbsp;&nbsp; * Try to scrim alot with fellow clan mates 
  </div>
  <div align="left" class="content_back">&nbsp;&nbsp;&nbsp; * Have Good Manners 
  </div>
  <div align="left" class="content_back">&nbsp;&nbsp;&nbsp; * Be a good CSer 
  </div>
  <div align="left" class="content_back">&nbsp;&nbsp;&nbsp; * and give us your best full potential. 
    <br />
  </div>
  <ul><h3 align="center" class="content_back">Counter-Strike: Source <a id="Css" name="Css"></a></h3>
  </ul>
  <p align="left" class="content_back">&nbsp;&nbsp;&nbsp; How to get all 7 Votes!</p>
  <div align="left" class="content_back">&nbsp;&nbsp;&nbsp; * Be active in Vent 
  </div>
  <div align="left" class="content_back">&nbsp;&nbsp;&nbsp; * Be active in Servers 
  </div>
  <div align="left" class="content_back">&nbsp;&nbsp;&nbsp; * Try to scrim alot with fellow clan mates 
  </div>
  <div align="left" class="content_back">&nbsp;&nbsp;&nbsp; * Have Good Manners 
  </div>
  <div align="left" class="content_back">&nbsp;&nbsp;&nbsp; * Be a good CSer 
  </div>
  <div style="TEXT-ALIGN: left">&nbsp;&nbsp;&nbsp; * and give us your best full potential. 
  </div>
  <ul>
    <p align="left" class="content_back">&nbsp;</p><h3 align="center" class="content_back">Diablo 2 <a id="d2" name="d2"></a></h3>
    <p align="left" class="content_back">&nbsp;Info To come! </p><h3 align="center" class="content_back">Halo 3 <a id="H3" name="H3"></a></h3>
    <p align="left" class="content_back">&nbsp;Info To come! </p><h3 align="center" class="content_back">World Of Warcraft <a id="wow" name="wow"></a></h3>
    <p align="left" class="content_back">&nbsp;Info To come! </p><h3 align="center" class="content_back">Warcraft III <a id="w3" name="w3"></a></h3>
    <p align="left" class="content_back">&nbsp;How to Join:
      <br />- Talk with a Grunt or higher and ask for a tryout. You can usually find somebody in channel clan ahwc.
      <br />- Don't make excuses. You don't need to win. You only need to show us that you're a decent player. 
      <br />- If your recruiter decides you're good enough to join then you should make a Di.____ account on bnet. Unless you have a ranked or a high level icon in which case you will not be required to start a new account
      <br />- Get added to the site, change your password, and ensure that your AIM(optional) and email are accurate
      <br />- Get a shaman to add you to our clan on battle.net (ahwc). 
      <br />- After joining be active on bnet and or the forums to pass your trial.&nbsp;
      <br /></p><h3 style="TEXT-ALIGN: center">&nbsp;<span style="FONT-WEIGHT: bold"><span>Empire At War</span></span></h3>
    <p align="left">-Join a recruiting game and play the host (you dont have to win but you must show skill and actually help team out) 
      <br />-Ask a member for a game, if member does not have rights get the name of a recruiter 
      <br />-If your recruiter decides you're good enough to join then you should make a Di.____ account (this is a must no exceptions) 
      <br />-Any BMing will result in the BMer being kicked from game 
      <br />-Give your name, email, and AIM(optional) to the recruiter. Log onto site and change password. Make sure all info is correct 
      <br />
      <br /></p>
  </ul>
</div>
