
<br />
<div class="content_back">
  <div align="center" style="color: rgb(21, 90, 194);">
    <div class="content_header"><h3 class="content_box_header">Our Vision</h3>
    </div>
  </div><hr class="cb" /><h4 style="text-align: center;">People. Passion. Performance.</h4><hr class="cb" />
  <p class="cb">									These three words define the purpose of Divine Intervention.  The idea is simply, as long as the People are happy and have a strong Passion for the clan, our Performance will always prosper.</p>
  <p class="cb"><span style="font-weight: bold;">People</span>– The People are everything to a clan. Regardless of rank, time, or influence, every Member counts.  The only way to achieve any vision in any organized group is by considering the people and their thoughts.  This is the first step to continuous success in Clan Di, one of our biggest aspirations is to ensure that every member is being heard, even when their opinion may be unfavorable or not shared by the majority.  By doing this, we maintain a high level of recognition, and all of our members feel more satisfied with their choice to experience gaming through our outlets and widespread community.</p>
  <p class="cb"><span style="font-weight: bold;">Passion </span>– When we achieve our goal pertaining to “the People” of the clan, we are ensuring that these people are satisfied with the gaming community they are involved in, thus increasing their passion and dedication to Divine Intervention.  Every member has the ability to make it to the top in Clan Di. Through pure passion for the clan, and dedication to the causes defined by the community, any member of Clan Di can prosper and become an amazing leader.</p>
  <p class="cb"><span style="font-weight: bold;">Performance</span> – Our Vision does not include limitations.  Members will always be recognized for their performance.  In Clan Di we strongly seek members interested in performing to the best of their abilities, as we aspire for our clan to excel and out perform and competition.  If the perseverance, persistence, and passion are there, the desired performance will be inevitable.

 </p>
  <p class="cb">This is what we wish to achieve, this is our vision.  As a member of this clan, you will come to realize that we do not believe in words such as “best” or “perfect” as anything more then a hyperbole, as there is ALWAYS room for improvement.  Our vision is a continuous cycle, and our people, our passion, and our performance will always thrive as long as there are members to see it through.</p><hr class="cb" />
  <div class="content_box_footer">&nbsp;
  
  
  
  
  
  
  
  
  
  </div>
</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
