
<br />
<div class="content_back">
  <div align="center">
    <div class="content_header"><h3 class="content_box_header">Rules</h3>
    </div>
  </div><hr class="cb" />
  <p class="cb">									Welcome to the <strong>Sovereign Login System</strong>. It is still a work in progress, but it is started to have several advanced features. Expect many more before its final release.</p><hr class="cb" />
  <div class="content_box_footer">
  </div>
</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
